apiVersion: apps/v1                     
kind: Deployment                          
metadata:                          
  name: posts-depl                      
spec: 
  replicas : 1        # number of pods we want to create   
  selector:           # find all the pods that have been created and get the ones with <posts>
    matchLabels:
      app: posts    
  template:           #confg for the pods -like the conf on post.yaml
    metadata:
      labels:
        app: posts  
    spec: 
      containers:
        - name: posts                  
          image: vagmaz/posts    # OR  image: vagmaz/posts:latest  
      
<br/>
<br/>

# Docker Commands

    1.  docker build -t <your_docker_id/image_name> .
    2.  docker exec -it <docker_id> .
    3.  docker run <image_name>
    4.  docker start <container_id>
    5.  docker system prune<br/>
<br/>

# Docker Commands

    1.  docker build -t <your_docker_id/image_name> .
    2.  docker exec -it <docker_id> .
    3.  docker run <image_name>
    4.  docker start <container_id>
    5.  docker system prune<br/>
<br/>

# Docker Commands

    1.  docker build -t <your_docker_id/image_name> .
    2.  docker exec -it <docker_id> .
    3.  docker run <image_name>
    4.  docker start <container_id>
    5.  docker system prune<br/>
<br/>

# Docker Commands

    1.  docker build -t <your_docker_id/image_name> .
    2.  docker exec -it <docker_id> .
    3.  docker run <image_name>
    4.  docker start <container_id>
    5.  docker system prune<br/>
<br/>

# Docker Commands

    1.  docker build -t <your_docker_id/image_name> .
    2.  docker exec -it <docker_id> .
    3.  docker run <image_name>
    4.  docker start <container_id>
    5.  docker system prune<br/>
<br/>

# Docker Commands

    1.  docker build -t <your_docker_id/image_name> .
    2.  docker exec -it <docker_id> .
    3.  docker run <image_name>
    4.  docker start <container_id>
    5.  docker system prune<br/>
<br/>

# Docker Commands

    1.  docker build -t <your_docker_id/image_name> .
    2.  docker exec -it <docker_id> .
    3.  docker run <image_name>
    4.  docker start <container_id>
    5.  docker system prune